# Generated by Django 4.1.5 on 2023-01-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogproject',
            name='post',
            field=models.TextField(default='value'),
        ),
        migrations.AlterField(
            model_name='blogproject',
            name='description',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='blogproject',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
